Traceback (most recent call last):
  File "/home/cegb03/Documentos/Facu Ema/DHS/DHS-Compilador_CEGB/src/main/python/App.py", line 55, in main
    caminante.visit(tree)
  File "/home/cegb03/Documentos/Facu Ema/DHS/DHS-Compilador_CEGB/.venv/lib/python3.12/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
           ^^^^^^^^^^^^^^^^^
  File "/home/cegb03/Documentos/Facu Ema/DHS/DHS-Compilador_CEGB/src/main/python/compiladoresParser.py", line 303, in accept
    return visitor.visitPrograma(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cegb03/Documentos/Facu Ema/DHS/DHS-Compilador_CEGB/src/main/python/Walker.py", line 74, in visitPrograma
    self.visit(ctx.instrucciones())
  File "/home/cegb03/Documentos/Facu Ema/DHS/DHS-Compilador_CEGB/.venv/lib/python3.12/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
           ^^^^^^^^^^^^^^^^^
  File "/home/cegb03/Documentos/Facu Ema/DHS/DHS-Compilador_CEGB/src/main/python/compiladoresParser.py", line 356, in accept
    return visitor.visitInstrucciones(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cegb03/Documentos/Facu Ema/DHS/DHS-Compilador_CEGB/src/main/python/Walker.py", line 84, in visitInstrucciones
    self.visit(ctx.instruccion())
  File "/home/cegb03/Documentos/Facu Ema/DHS/DHS-Compilador_CEGB/.venv/lib/python3.12/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
           ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'accept'
